// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PLUS-0]
	_ = x[MINUS-1]
	_ = x[STAR-2]
	_ = x[SLASH-3]
	_ = x[PAREN_OPEN-4]
	_ = x[PAREN_CLOSE-5]
	_ = x[NUMBER-6]
	_ = x[EOL-7]
}

const _TokenType_name = "PLUSMINUSSTARSLASHPAREN_OPENPAREN_CLOSENUMBEREOL"

var _TokenType_index = [...]uint8{0, 4, 9, 13, 18, 28, 39, 45, 48}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
